// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace TournamentScheduler.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231027162424_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Competition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DefeatPoints")
                        .HasColumnType("integer");

                    b.Property<int>("DrawPoints")
                        .HasColumnType("integer");

                    b.Property<string>("Teams")
                        .HasColumnType("text");

                    b.Property<int>("VictoryPoints")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Competitions");
                });
#pragma warning restore 612, 618
        }
    }
}
